# Generated by Django 4.2.5 on 2023-11-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='booking_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
