# Generated by Django 4.2.5 on 2023-12-04 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bookinginfo_booking_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookingInfo',
            new_name='customerPurchaseInfo',
        ),
        migrations.RenameField(
            model_name='customerpurchaseinfo',
            old_name='booking_id',
            new_name='customer_ref',
        ),
    ]
